In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from scipy.fftpack import fft2

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv


In [2]:
train = pd.read_csv('../input/digit-recognizer/train.csv')
col = ['pixel%d'%i for i in range(784)]

In [3]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
train[col].values[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 188, 255,  94,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 191, 250, 253,  93,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [5]:
x0 = train[col].values[0].reshape((28,28))
x0.shape

(28, 28)

In [6]:
x0

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 188, 255,  94,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 191, 250, 253,  93,   0,   0,   0,
          0,   0],
       [  

In [7]:
%%time
x0_rfft = np.fft.rfft2(x0)

CPU times: user 7.19 ms, sys: 2.53 ms, total: 9.73 ms
Wall time: 47 ms


In [8]:
x0_rfft.shape

(28, 15)

In [9]:
x0_rfft.max()

(16649+0j)

In [10]:
x0_rfft.min()

(-12908.05643717838-1555.701841509453j)

In [11]:
x0_rfft.flatten().shape

(420,)

In [12]:
x0_rfft.shape

(28, 15)

In [13]:
x0_rfft

array([[ 1.66490000e+04+0.00000000e+00j, -1.08257306e+04-3.93923615e+02j,
         6.76963766e+02+1.41636972e+03j,  2.97274741e+03-1.34466589e+03j,
        -3.31791733e+02-3.04834641e+02j, -1.63018608e+03+1.11894742e+03j,
         8.00741748e+02-1.77269418e+02j,  8.00000000e+01-4.79000000e+02j,
         1.45728115e+02-3.32592893e+01j, -3.63814434e+02+3.11774740e+02j,
         5.22944866e+01+1.19955661e+02j,  3.26164236e+02-2.52630345e+02j,
        -3.64936381e+02-1.42308333e+02j,  9.58194557e+01+3.16905219e+02j,
         8.30000000e+01+0.00000000e+00j],
       [-6.49126199e+03-6.99140171e+02j,  1.48266475e+04+1.64546469e+03j,
        -1.29080564e+04-1.55570184e+03j,  3.60347777e+03+1.80672095e+03j,
         2.23228880e+03-1.91617800e+03j, -1.36095077e+03+7.49407401e+02j,
        -7.48178114e+02+4.66608810e+02j,  6.28439372e+02-3.31641365e+02j,
         8.05692084e+01-1.64158199e+02j,  7.83334451e+01-5.70929944e+01j,
        -3.68890040e+02+2.83445422e+02j,  1.32580306e+02+4.15574176e+0

In [14]:
%%time
x0_hfft = np.fft.hfft(x0)

CPU times: user 3.13 ms, sys: 1.57 ms, total: 4.71 ms
Wall time: 6.13 ms


In [15]:
x0_hfft.shape

(28, 54)

In [16]:
x0_hfft_2 = np.fft.hfft(x0/255)
x0_hfft_2.shape

(28, 54)

In [17]:
x0_hfft_2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
x0_hfft_2.min()

-7.597613931728981

In [19]:
x0_hfft_2.max()

8.258823529411764

In [20]:
x0_rfft_2 = np.fft.rfft2(x0/255, norm="ortho")
x0_rfft_2.shape

(28, 15)

In [21]:
x0.shape

(28, 28)

In [22]:
x0_hfft

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
x0_rfft_3 = np.matrix(np.fft.fft2(x0))
x0_rfft_3.shape

(28, 28)

In [24]:
x0_rfft_3_H = x0_rfft_3.getH()
x0_rfft_3_H.shape

(28, 28)

In [25]:
np.real(x0_rfft_3) - np.real(x0_rfft_3_H)

matrix([[ 0.00000000e+00, -4.33446859e+03,  3.88124765e+03,
          3.49620365e+03, -1.44875742e+03, -2.93099044e+03,
          5.70642373e+02,  6.07000000e+02,  4.03259515e+02,
         -3.44573677e+02,  1.36109972e+02,  3.75262654e+02,
         -5.85502096e+02,  3.59566411e+02, -3.70000000e+02,
          3.59566411e+02, -5.85502096e+02,  3.75262654e+02,
          1.36109972e+02, -3.44573677e+02,  4.03259515e+02,
          6.07000000e+02,  5.70642373e+02, -2.93099044e+03,
         -1.44875742e+03,  3.49620365e+03,  3.88124765e+03,
         -4.33446859e+03],
        [ 4.33446859e+03,  0.00000000e+00, -1.10442981e+04,
          6.26211590e+03,  3.52986305e+03, -1.13426453e+03,
         -1.61029989e+03, -2.45764196e+02,  1.49630946e+02,
          3.14092546e+02, -2.18150433e+02,  1.74894487e+02,
          5.30854334e+02, -7.36612459e+02,  5.32771774e+02,
         -2.86624597e+02,  7.83844326e+01, -3.07914000e+02,
          1.58734026e+02,  6.28958237e+01, -2.95126045e+02,
          7.6

In [26]:
x0_rfft_3[0,1]

(-10825.730587917198-393.9236150389595j)

In [27]:
x0_rfft_3.item((0,1))

(-10825.730587917198-393.9236150389595j)

In [28]:
x0_rfft_3.item((1,0))

(-6491.2619930420415-699.1401706430707j)

In [29]:
x0_rfft_3_H.item((1,0))

(-10825.730587917198+393.9236150389595j)

In [30]:
np.real(x0_rfft_3).item((0,27))

-10825.730587917198

In [31]:
x0_rfft_3p = np.matrix(fft2(x0))
x0_rfft_3p.shape

(28, 28)

In [32]:
x0_rfft_3

matrix([[ 1.66490000e+04+0.00000000e+00j,
         -1.08257306e+04-3.93923615e+02j,
          6.76963766e+02+1.41636972e+03j,
          2.97274741e+03-1.34466589e+03j,
         -3.31791733e+02-3.04834641e+02j,
         -1.63018608e+03+1.11894742e+03j,
          8.00741748e+02-1.77269418e+02j,
          8.00000000e+01-4.79000000e+02j,
          1.45728115e+02-3.32592893e+01j,
         -3.63814434e+02+3.11774740e+02j,
          5.22944866e+01+1.19955661e+02j,
          3.26164236e+02-2.52630345e+02j,
         -3.64936381e+02-1.42308333e+02j,
          9.58194557e+01+3.16905219e+02j,
          8.30000000e+01+6.66133815e-16j,
          9.58194557e+01-3.16905219e+02j,
         -3.64936381e+02+1.42308333e+02j,
          3.26164236e+02+2.52630345e+02j,
          5.22944866e+01-1.19955661e+02j,
         -3.63814434e+02-3.11774740e+02j,
          1.45728115e+02+3.32592893e+01j,
          8.00000000e+01+4.79000000e+02j,
          8.00741748e+02+1.77269418e+02j,
         -1.63018608e+03-1.1189474

In [33]:
x0_rfft_3p

matrix([[ 1.66490000e+04+0.00000000e+00j,
         -1.08257306e+04-3.93923615e+02j,
          6.76963766e+02+1.41636972e+03j,
          2.97274741e+03-1.34466589e+03j,
         -3.31791733e+02-3.04834641e+02j,
         -1.63018608e+03+1.11894742e+03j,
          8.00741748e+02-1.77269418e+02j,
          8.00000000e+01-4.79000000e+02j,
          1.45728115e+02-3.32592893e+01j,
         -3.63814434e+02+3.11774740e+02j,
          5.22944866e+01+1.19955661e+02j,
          3.26164236e+02-2.52630345e+02j,
         -3.64936381e+02-1.42308333e+02j,
          9.58194557e+01+3.16905219e+02j,
          8.30000000e+01-1.68753900e-13j,
          9.58194557e+01-3.16905219e+02j,
         -3.64936381e+02+1.42308333e+02j,
          3.26164236e+02+2.52630345e+02j,
          5.22944866e+01-1.19955661e+02j,
         -3.63814434e+02-3.11774740e+02j,
          1.45728115e+02+3.32592893e+01j,
          8.00000000e+01+4.79000000e+02j,
          8.00741748e+02+1.77269418e+02j,
         -1.63018608e+03-1.1189474